services:
  - type: web
    name: mindshot-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python mindshot_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: PORT
        value: 10000 